### ISSUE TITLE
Unable to build whisker

### ISSUE THREAD

**Issue by cameronweibel** [se2p/whisker#10]
I'm unable to build whisker (I have tsc -v 4.5.2 and webpack 4.46.0). Almost certainly this is a problem on my side? Thanks for your help!

![image](https://user-images.githubusercontent.com/8155129/143763153-f3bd0811-4be9-46ea-9a93-0d757e747fb4.png)

**Comment by marvinkreis** [comment]
Looks like `tsc --incremental; webpack --progress --colors --bail` is getting interpreted as one command instead of two. Might be a Windows problem.

You could try replacing the line `        "build": "tsc --incremental; webpack --progress --colors --bail",` with `        "build": "tsc --incremental && webpack --progress --colors --bail",` in `whisker-main/package.json`. I don't have an installation to try it on right now, but it might work.

**Comment by cameronweibel** [comment]
I'll switch to Linux, thanks.
